language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"

env:
  - PYCOUNTRY_VERSION=1.11

install:
  - "pip install ."
  - "pip install unittest2"
  - "pip install pycountry==$PYCOUNTRY_VERSION"

script: nosetests
